// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.coffeeroo.domain;

import com.j1987.coffeeroo.domain.JAnalysis;
import com.j1987.coffeeroo.domain.JAnalysisDataOnDemand;
import com.j1987.coffeeroo.domain.JAnalysisIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JAnalysisIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JAnalysisIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JAnalysisIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JAnalysisIntegrationTest: @Transactional;
    
    @Autowired
    JAnalysisDataOnDemand JAnalysisIntegrationTest.dod;
    
    @Test
    public void JAnalysisIntegrationTest.testCountJAnalyses() {
        Assert.assertNotNull("Data on demand for 'JAnalysis' failed to initialize correctly", dod.getRandomJAnalysis());
        long count = JAnalysis.countJAnalyses();
        Assert.assertTrue("Counter for 'JAnalysis' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JAnalysisIntegrationTest.testFindJAnalysis() {
        JAnalysis obj = dod.getRandomJAnalysis();
        Assert.assertNotNull("Data on demand for 'JAnalysis' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JAnalysis' failed to provide an identifier", id);
        obj = JAnalysis.findJAnalysis(id);
        Assert.assertNotNull("Find method for 'JAnalysis' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JAnalysis' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JAnalysisIntegrationTest.testFindAllJAnalyses() {
        Assert.assertNotNull("Data on demand for 'JAnalysis' failed to initialize correctly", dod.getRandomJAnalysis());
        long count = JAnalysis.countJAnalyses();
        Assert.assertTrue("Too expensive to perform a find all test for 'JAnalysis', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JAnalysis> result = JAnalysis.findAllJAnalyses();
        Assert.assertNotNull("Find all method for 'JAnalysis' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JAnalysis' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JAnalysisIntegrationTest.testFindJAnalysisEntries() {
        Assert.assertNotNull("Data on demand for 'JAnalysis' failed to initialize correctly", dod.getRandomJAnalysis());
        long count = JAnalysis.countJAnalyses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JAnalysis> result = JAnalysis.findJAnalysisEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JAnalysis' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JAnalysis' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JAnalysisIntegrationTest.testFlush() {
        JAnalysis obj = dod.getRandomJAnalysis();
        Assert.assertNotNull("Data on demand for 'JAnalysis' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JAnalysis' failed to provide an identifier", id);
        obj = JAnalysis.findJAnalysis(id);
        Assert.assertNotNull("Find method for 'JAnalysis' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJAnalysis(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JAnalysis' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JAnalysisIntegrationTest.testMergeUpdate() {
        JAnalysis obj = dod.getRandomJAnalysis();
        Assert.assertNotNull("Data on demand for 'JAnalysis' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JAnalysis' failed to provide an identifier", id);
        obj = JAnalysis.findJAnalysis(id);
        boolean modified =  dod.modifyJAnalysis(obj);
        Integer currentVersion = obj.getVersion();
        JAnalysis merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JAnalysis' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JAnalysisIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JAnalysis' failed to initialize correctly", dod.getRandomJAnalysis());
        JAnalysis obj = dod.getNewTransientJAnalysis(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JAnalysis' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JAnalysis' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'JAnalysis' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JAnalysisIntegrationTest.testRemove() {
        JAnalysis obj = dod.getRandomJAnalysis();
        Assert.assertNotNull("Data on demand for 'JAnalysis' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JAnalysis' failed to provide an identifier", id);
        obj = JAnalysis.findJAnalysis(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JAnalysis' with identifier '" + id + "'", JAnalysis.findJAnalysis(id));
    }
    
}
