// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.coffeeroo.domain;

import com.j1987.coffeeroo.domain.JBill;
import com.j1987.coffeeroo.domain.JBillDataOnDemand;
import com.j1987.coffeeroo.domain.JBillIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JBillIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JBillIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JBillIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JBillIntegrationTest: @Transactional;
    
    @Autowired
    JBillDataOnDemand JBillIntegrationTest.dod;
    
    @Test
    public void JBillIntegrationTest.testCountJBills() {
        Assert.assertNotNull("Data on demand for 'JBill' failed to initialize correctly", dod.getRandomJBill());
        long count = JBill.countJBills();
        Assert.assertTrue("Counter for 'JBill' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JBillIntegrationTest.testFindJBill() {
        JBill obj = dod.getRandomJBill();
        Assert.assertNotNull("Data on demand for 'JBill' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JBill' failed to provide an identifier", id);
        obj = JBill.findJBill(id);
        Assert.assertNotNull("Find method for 'JBill' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JBill' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JBillIntegrationTest.testFindAllJBills() {
        Assert.assertNotNull("Data on demand for 'JBill' failed to initialize correctly", dod.getRandomJBill());
        long count = JBill.countJBills();
        Assert.assertTrue("Too expensive to perform a find all test for 'JBill', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JBill> result = JBill.findAllJBills();
        Assert.assertNotNull("Find all method for 'JBill' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JBill' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JBillIntegrationTest.testFindJBillEntries() {
        Assert.assertNotNull("Data on demand for 'JBill' failed to initialize correctly", dod.getRandomJBill());
        long count = JBill.countJBills();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JBill> result = JBill.findJBillEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JBill' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JBill' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JBillIntegrationTest.testFlush() {
        JBill obj = dod.getRandomJBill();
        Assert.assertNotNull("Data on demand for 'JBill' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JBill' failed to provide an identifier", id);
        obj = JBill.findJBill(id);
        Assert.assertNotNull("Find method for 'JBill' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJBill(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JBill' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JBillIntegrationTest.testMergeUpdate() {
        JBill obj = dod.getRandomJBill();
        Assert.assertNotNull("Data on demand for 'JBill' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JBill' failed to provide an identifier", id);
        obj = JBill.findJBill(id);
        boolean modified =  dod.modifyJBill(obj);
        Integer currentVersion = obj.getVersion();
        JBill merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JBill' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JBillIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JBill' failed to initialize correctly", dod.getRandomJBill());
        JBill obj = dod.getNewTransientJBill(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JBill' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JBill' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'JBill' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JBillIntegrationTest.testRemove() {
        JBill obj = dod.getRandomJBill();
        Assert.assertNotNull("Data on demand for 'JBill' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JBill' failed to provide an identifier", id);
        obj = JBill.findJBill(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JBill' with identifier '" + id + "'", JBill.findJBill(id));
    }
    
}
