// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.coffeeroo.domain;

import com.j1987.coffeeroo.domain.JBridge;
import com.j1987.coffeeroo.domain.JBridgeDataOnDemand;
import com.j1987.coffeeroo.domain.JFactoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect JBridgeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JBridgeDataOnDemand: @Component;
    
    private Random JBridgeDataOnDemand.rnd = new SecureRandom();
    
    private List<JBridge> JBridgeDataOnDemand.data;
    
    @Autowired
    JFactoryDataOnDemand JBridgeDataOnDemand.jFactoryDataOnDemand;
    
    public JBridge JBridgeDataOnDemand.getNewTransientJBridge(int index) {
        JBridge obj = new JBridge();
        setCode(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void JBridgeDataOnDemand.setCode(JBridge obj, int index) {
        String code = "code_" + index;
        obj.setCode(code);
    }
    
    public void JBridgeDataOnDemand.setName(JBridge obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public JBridge JBridgeDataOnDemand.getSpecificJBridge(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        JBridge obj = data.get(index);
        Long id = obj.getId();
        return JBridge.findJBridge(id);
    }
    
    public JBridge JBridgeDataOnDemand.getRandomJBridge() {
        init();
        JBridge obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return JBridge.findJBridge(id);
    }
    
    public boolean JBridgeDataOnDemand.modifyJBridge(JBridge obj) {
        return false;
    }
    
    public void JBridgeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = JBridge.findJBridgeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'JBridge' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<JBridge>();
        for (int i = 0; i < 10; i++) {
            JBridge obj = getNewTransientJBridge(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
