// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.coffeeroo.domain;

import com.j1987.coffeeroo.domain.JFirm;
import com.j1987.coffeeroo.domain.JFirmDataOnDemand;
import com.j1987.coffeeroo.domain.JFirmIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JFirmIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JFirmIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JFirmIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JFirmIntegrationTest: @Transactional;
    
    @Autowired
    JFirmDataOnDemand JFirmIntegrationTest.dod;
    
    @Test
    public void JFirmIntegrationTest.testCountJFirms() {
        Assert.assertNotNull("Data on demand for 'JFirm' failed to initialize correctly", dod.getRandomJFirm());
        long count = JFirm.countJFirms();
        Assert.assertTrue("Counter for 'JFirm' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JFirmIntegrationTest.testFindJFirm() {
        JFirm obj = dod.getRandomJFirm();
        Assert.assertNotNull("Data on demand for 'JFirm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JFirm' failed to provide an identifier", id);
        obj = JFirm.findJFirm(id);
        Assert.assertNotNull("Find method for 'JFirm' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JFirm' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JFirmIntegrationTest.testFindAllJFirms() {
        Assert.assertNotNull("Data on demand for 'JFirm' failed to initialize correctly", dod.getRandomJFirm());
        long count = JFirm.countJFirms();
        Assert.assertTrue("Too expensive to perform a find all test for 'JFirm', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JFirm> result = JFirm.findAllJFirms();
        Assert.assertNotNull("Find all method for 'JFirm' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JFirm' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JFirmIntegrationTest.testFindJFirmEntries() {
        Assert.assertNotNull("Data on demand for 'JFirm' failed to initialize correctly", dod.getRandomJFirm());
        long count = JFirm.countJFirms();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JFirm> result = JFirm.findJFirmEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JFirm' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JFirm' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JFirmIntegrationTest.testFlush() {
        JFirm obj = dod.getRandomJFirm();
        Assert.assertNotNull("Data on demand for 'JFirm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JFirm' failed to provide an identifier", id);
        obj = JFirm.findJFirm(id);
        Assert.assertNotNull("Find method for 'JFirm' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJFirm(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JFirm' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JFirmIntegrationTest.testMergeUpdate() {
        JFirm obj = dod.getRandomJFirm();
        Assert.assertNotNull("Data on demand for 'JFirm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JFirm' failed to provide an identifier", id);
        obj = JFirm.findJFirm(id);
        boolean modified =  dod.modifyJFirm(obj);
        Integer currentVersion = obj.getVersion();
        JFirm merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JFirm' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JFirmIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JFirm' failed to initialize correctly", dod.getRandomJFirm());
        JFirm obj = dod.getNewTransientJFirm(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JFirm' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JFirm' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'JFirm' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JFirmIntegrationTest.testRemove() {
        JFirm obj = dod.getRandomJFirm();
        Assert.assertNotNull("Data on demand for 'JFirm' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JFirm' failed to provide an identifier", id);
        obj = JFirm.findJFirm(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JFirm' with identifier '" + id + "'", JFirm.findJFirm(id));
    }
    
}
